site_name: My Docs
# site_url: https://mydomain.org/mysite
theme:
  name: material
extra:
  alternate:
    - name: Chinese (Simplified)
      link: / 
      lang: zh
    - name: Chinese (Taiwanese)
      link: /zh_Hant/
      lang: zh-Hant