site_name: My Docs
# site_url: https://mydomain.org/mysite
theme:
  name: material
plugins:
  - i18n:
      docs_structure: suffix
      languages:
        - locale: zh
          default: true
          name: 中文简体
          build: true
          link: /MkDocs/
        - locale: zh-Hant
          name: 中文繁体（台湾）
          build: true
          link: /MkDocs/